language: go
go:
 - "1.13.x"

env:
  - GO111MODULE=on

install: true

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.22.2

script:
  - go mod init
  - go mod download
  - ls -la vendor/github.com/sirupsen/logrus
  - go test -v -mod=vendor ./...
  - GOPACKAGESPRINTGOLISTERRORS=1 GL_DEBUG=linters_output golangci-lint run
